-- aimccoy

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS Campuses;
DROP TABLE IF EXISTS Fees;
DROP TABLE IF EXISTS Degrees;
DROP TABLE IF EXISTS Enrollments;
DROP TABLE IF EXISTS Disciplines;
DROP TABLE IF EXISTS DiscEnroll;
DROP TABLE IF EXISTS Faculty;
SET FOREIGN_KEY_CHECKS = 1;
